config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :sign_out_via => [ :get, :delete ]
  resources :authors
  resources :books

  get 'conversations', to: 'conversations#index', as: 'conversations'
  get 'conversation/get_chat/:conversation_id', to: 'messages#get_conversation', as: 'get_conversation'
  get 'conversations/new/:sender_id/:receiver_id', to: 'conversations#create', as: 'create_conversation'
  post 'conversations/new/:sender_id/:receiver_id', to: 'conversations#create', as: 'new_conversation'
  get 'conversation/conv=:conversation_id', to: 'messages#index', as: 'conversation_messages'
  post 'conversation/new/:conversation_id', to: 'messages#create', as: 'conversation_messages_create'
  get 'users/index', to: 'users#index', as: 'user_index'
  get 'users/profile/:id/', to: 'users#profile', as: 'user_profile'
  get 'users/profile/:id/reviews/', to: 'users#reviews', as: 'user_reviews'
  get 'users/profile/:id/friends/', to: 'users#friends', as: 'user_friends'
  get 'user/profile/:id/forum', to: 'users#forum', as: 'user_forum'
  get 'user/profile/:id/recommandations', to: 'users#recommandations', as: 'user_recs'
  post 'user/profile/:id/comments/new', to:'comments#comment_new_user', as: 'comment_new_user'
  get 'users/profile/:id/list', to:'users#list', as: 'list'
  get 'users/profile/edit_list/:id_user_book/', to: 'users#details', as: 'list_book_details'
  patch 'users/profile/edit_list/:id_user_book/', to:'users#update_list', as: 'book_update_list_adv'
  get 'users/profile/edit_list/:id_user_book/remove', to:'users#remove_list', as: 'remove_list'
  post 'books/user_list/:id/', to:'books#add_to_list', as: 'book_add_list'
  patch 'books/user_list/:id/', to:'books#update_list', as: 'book_update_list'
  post 'book/:id/comments/new', to:'comments#comment_new_book', as: 'comment_new_book'
  get 'author/delete/:id', to: 'authors#destroy', as: 'author_delete'
  post 'author/:id/comments/new', to:'comments#comment_new_author', as: 'comment_new_author'
  get 'search_results', to: 'search#search', as: 'search'
  get 'myreviews/new/:book_id', to: 'reviews#new', as: 'review_new'
  post 'myreviews/new/:book_id/create', to: 'reviews#create', as: 'review_create'
  get 'myreviews/:review_id/edit', to: 'reviews#edit', as: 'review_edit'
  patch 'myreviews/:review_id/edit', to: 'reviews#update', as: 'review_update'
  get 'myreviews/:review_id/delete', to: 'reviews#destroy', as: 'review_delete'
  get 'myreviews/:review_id/like', to: 'reviews#like', as: 'review_like'
  get 'myreviews/:review_id/dislike', to: 'reviews#dislike', as: 'review_dislike'
  get 'books/reviews/:id', to: 'books#reviews', as: 'book_reviews'
  get 'books/editions/:id', to: 'books#editions', as: 'book_editions'
  get 'books/recommandations/:id', to: 'books#recommandations', as: 'book_recommandations'
  get 'books/stats/:id', to: 'books#stats', as: 'book_stats'
  delete 'books/delete/:id', to: 'books#destroy', as: 'book_delete'
  get 'books/delete/:id' => 'books#destroy'
  get 'book/:book_id/editions/new/', to: 'editions#new', as: 'edition_new'
  post 'book/:book_id/editions/new/create', to: 'editions#create', as: 'edition_create'
  get 'editions/:edition_id/delete', to: 'editions#destroy', as: 'edition_delete'
  get 'editions/:edition_id/edit', to: 'editions#edit', as: 'edition_edit'
  patch 'editions/:edition_id/edit', to: 'editions#update', as: 'edition_update'
  get 'comment/:comment_id/edit', to:'comments#edit', as: 'comment_edit'
  patch 'comment/:comment_id/edit', to:'comments#comment_update', as: 'comment_update'
  get 'comment/:comment_id/delete', to: 'comments#comment_delete', as: 'comment_delete'
  get 'comment/:comment_id/like', to: 'comments#like', as: 'comment_like'
  get 'comment/:comment_id/dislike', to: 'comments#dislike', as: 'comment_dislike'
  get 'add_friend/:id', to: 'users#add_friend', as: 'add_friend'
  get 'remove_friend/:id', to: 'users#remove_friend', as: 'remove_friend'
  get 'friend_requests', to: 'users#requests', as: 'friend_requests'
  get 'accept_request/:id', to: "users#accept_request", as: 'accept_request'
  get 'decline_request/:id', to: "users#decline_request", as: 'decline_request'
  get 'cancel_request/:id', to: 'users#cancel_request', as: 'cancel_request'
  get 'home', to: 'users#home', as: 'home'
  get 'recommandation/new/:book_id', to: 'recommandations#new', as: 'rec_new'
  post 'recommandation/create/:book_id', to: 'recommandations#create', as: 'rec_create'
  get 'recommandation/:id/destroy', to: 'recommandations#destroy', as: 'rec_destroy'
  get 'forum', to: 'category#forum', as: 'forum'
  get 'forum/:category_id', to: 'category#show', as: 'category'
  get 'forum/topic/:topic_id', to: 'topics#show', as: 'topic'
  post 'forum/topic/:topic_id', to:'comments#comment_new_topic', as: 'comment_new_topic'
  get 'forum/topic/:topic_id/like', to: 'topics#like', as: 'topic_like'
  get 'forum/topic/:topic_id/dislike', to: 'topics#dislike', as: 'topic_dislike'
  get 'forum/new/:category_id/topic/', to: 'topics#new', as: 'topic_new'
  post 'forum/new/:category_id/topic/', to: 'topics#create', as: 'topic_create'
  get 'forum/topic/:topic_id/edit', to: 'topics#edit', as: 'topic_edit'
  patch 'forum/topic/:topic_id/edit', to: 'topics#update', as: 'topic_update'
  get 'forum/topic/:topic_id/delete', to: 'topics#destroy', as: 'topic_delete'



  authenticated :user do
    root 'users#home', as: :authenticated_root
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end


  get "*path" => redirect("/"), alert: "This page does not exist"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/topic.rb
class Topic < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :comments, as: :commentable, dependent: :destroy
  validates_presence_of :title
  validates_presence_of :body
  validates_presence_of :user_id
  validates_presence_of :category_id
  acts_as_votable
  include PublicActivity::Common

  def self.last_post(tid)
    _topic = Topic.find(tid)
    if _topic.comments.last
      return _topic.comments.last
      else return _topic
    end
  end


  def self.delete_activities(cid)
    acts = PublicActivity::Activity.where(trackable_id: cid, trackable_type: "Topic")
    acts.destroy_all
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :is_user, only: [:new, :create, :edit, :update, :destroy, :like, :dislike]
  before_action :category_exist, only: [:new,:create]
  before_action :topic_exist, only: [:edit,:update,:destroy, :like, :dislike]
  def show
    @topic = Topic.find(params[:topic_id])
    @comments = @topic.comments
    @comments = @comments.paginate(page: params[:page], per_page: 2)
  end

  def new
    @topic = Topic.new
    @category = Category.find(params[:category_id])
  end


  def create
    @topic = Topic.new(:body=>params[:body],:title=>params[:title],:category_id=>params[:category_id],:user_id=>current_user.id)
    @category = Category.find(params[:category_id])
    if @topic.valid?
      @topic.save
      @topic.create_activity(:topic, :owner => current_user)
      redirect_to topic_path(@topic), notice: 'Your topic has been posted.'
    else
      render 'topicnew'
    end
  end

  def edit
    @topic = Topic.find(params[:topic_id])
    if (current_user.id == (@topic.user_id) || current_user.try(:admin?))
      @category = Category.find(@topic.category_id)
    else redirect_to topic_path(@topic), :alert => "You don't have the rights to acces this page."
    end
  end

  def update
    @topic = Topic.find(params[:topic_id])
    if (current_user.id == (@topic.user_id) || current_user.try(:admin?))
      if @topic.update(:body=>params[:topic][:body],:title=>params[:topic][:title])
        redirect_to topic_path(@topic), :notice => "The topic has been updated."
      else
        render 'topicedit'
      end
    else redirect_to topic_path(@topic), :notice => "You don't have the rights to acces this page."
    end
  end

  def destroy
    @topic = Topic.find(params[:topic_id])
    if (current_user.id == (@topic.user_id) || current_user.try(:admin?))
      @topic.destroy
      Topic.delete_activities(@topic.id)
      redirect_to category_path(@topic.category_id), :notice => "Your topic has been deleted."
    else redirect_to topic_path(@topic), :alert => "You don't have the rights to acces this page."
    end
  end

  def like
    @topic = Topic.find(params[:topic_id])
    if current_user.voted_up_on?(@topic)
      @topic.unliked_by current_user
    else
      @topic.upvote_by current_user
    end
    redirect_back fallback_location: root_path

  end

  def dislike
    @topic = Topic.find(params[:topic_id])
    if current_user.voted_down_on?(@topic)
      @topic.undisliked_by current_user
    else
      @topic.downvote_by current_user
    end
    redirect_back fallback_location: root_path
  end

  def is_user
    if !user_signed_in?
      redirect_to root_path, :alert => "You don't have the rights to acces this page."
    end
  end

  def category_exist
    if not Category.exists?params[:category_id]
      redirect_to root_path, alert: 'The category does not exist. '
    end
  end

  def topic_exist
    if not Topic.exists?params[:topic_id]
      redirect_to root_path, alert: 'The topic does not exist.'
    end
  end
end

app/helpers/topic_helper.rb
module TopicHelper
end

app/views/topics/edit.html.erb
<div class="container-form"><h1>Edit your Topic: <%=link_to @topic.title, topic_path(@topic), class: 'link' %></h1>
  <%= form_for(@topic, url: topic_update_path(@topic.id), html: {method: "patch"}) do |f| %>
    <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@topic.errors.count, "error") %> prohibited
          this topic from being saved:
        </h2>
        <ul>
          <% @topic.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <%= f.label 'Topic Title ', class: "label-form col-25 " %>
      <%= f.text_field 'title',class: "input-form col-75 " %>
    </div>
    <div class="row">
      <%= f.label 'Topic Body ', class: "label-form col-25 " %>
      <%= f.text_area 'body' ,class: "input-form col-75 "%>
    </div>
    <br>
    <%= f.submit 'Save topic', class: "big-button link" %>
  <% end %></div>

app/views/topics/new.html.erb
<div class="container-form"><h1>New topic in <%=link_to @category.name, @category, class: "link" %></h1>
  <%= form_tag(topic_create_path,method: :post) do %>
    <% if @topic.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@topic.errors.count, "error") %> prohibited
          this topic from being saved:
        </h2>
        <ul>
          <% @topic.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <%= label_tag 'Topic Title ',nil, class: "label-form col-25 " %>
      <%= text_field_tag 'title',nil,class: "input-form col-75 " %>
    </div>
    <div class= "row">
      <%= label_tag 'Topic Content ',nil, class: "label-form col-25 " %>
      <%= text_area_tag 'body',nil,class: "input-form col-75 " %>
    </div>
    <br>
    <%= submit_tag 'Create topic', class: "big-button link" %>
  <% end %></div>

app/views/topics/show.html.erb
<div class="container-title container-form"><h1>Topic title: <%= @topic.title %></h1>
<label style="float: left">Back to: <%= link_to @topic.category.name , category_path(@topic.category), class: "link"%>,
  <%= link_to 'Forum',forum_path, class: "link"%></label>
<br></div>

<div class="container-text div-padding container-post">
  <% if @topic.user.avatar.exists? %>
    <%= image_tag @topic.user.avatar.url(:thumb), :style=>"float: left" %>
  <% else %> <%= image_tag('No_Image_Available.png', size: "100x100", alt: 'no_image', style: "float: left" ) %>
  <% end %>
  <strong>Posted by: </strong> <%= link_to @topic.user.username, user_profile_path(@topic.user.username) %>
  <br>
  <em>Created at </em><%= @topic.created_at %></em>
  <br>
  <%= @topic.get_upvotes.size.to_s + " out of " + (@topic.get_downvotes.size + @topic.get_upvotes.size).to_s + " users found this topic helpful. " %>
  <br>
  <br>
  <br>

  <%= simple_format @topic.body %>
  <br>
  <% if user_signed_in? %>

    <div style="display: inline">
      <div style="float: left">
        <% if current_user.voted_up_on?(@topic) %>
          <%= link_to '👍',topic_like_path(@topic), method: :put, class:"icon-on" %>
        <% else %>
          <%= link_to '👍',topic_like_path(@topic), method: :put, class:"icon" %>
        <% end %>



        <% if current_user.voted_down_on?(@topic) %>
          <%= link_to '👎',topic_dislike_path(@topic), method: :put, class:"icon-on" %>
        <% else %>
          <%= link_to '👎',topic_dislike_path(@topic), method: :put, class:"icon" %>
        <% end%>
      </div>

      <div style="float: right">
        <% if current_user.id == @topic.user_id || current_user.try(:admin?) %>
          <%= link_to '✎', topic_edit_path(@topic), class:"icon" %>
          <%= link_to '🗑️', topic_delete_path(@topic),
                      :onclick => "return confirm('Are you sure you want to delete this topic?')", class:"icon" %>
        <% end %>
      </div>
    </div>
        <%end%>
  <br>
  <br>
</div>

<div class="container-post">
    <br>
    <div class="container-title-new continer-form">
      <h4 class="same-row-title">Replies</h4>
      <label class="dropdown " style="float: right; padding-top: 5px;">
        <div class="dropbtn link">Sort comments ▼</div> <div class="dropdown-content">
        <%= link_to "Best", topic_path(@topic) %>
        <%= link_to "Most Likes", topic_path(@topic, :sort => "like") %>
        <%= link_to "Most Disikes", topic_path(@topic, :sort => "dislike") %>
        <%= link_to "Oldest", topic_path(@topic, :sort => "old") %>
        <%= link_to "Newest", topic_path(@topic, :sort => "new") %>
      </div>
      </label>
    </div>
    <% if @comments.count > 0 %>
      <% @comments.each do |comment| %>
        <div class="container-text div-padding container-post">
          <% if User.find(comment.user_id).avatar.exists? %>
            <%= image_tag User.find(comment.user_id).avatar.url(:thumb), style: "float: left" %>
          <% else %> <%= image_tag('No_Image_Available.png', size: "100x100", alt: 'no_image', style: "float: left") %>
          <% end %>
          <strong>Reply by:</strong><%= link_to comment.user.username, user_profile_path(comment.user.username) %>
          <br>
          <em>Posted at <%= comment.created_at %></em>
          <br>
          <%= comment.get_upvotes.size.to_s + " out of " + (comment.get_downvotes.size + comment.get_upvotes.size).to_s + " users found this comment helpful. " %>

          <br>
          <br>
          <br>
          <%= simple_format comment.body %>
          <br>
          <% if user_signed_in? %>

            <div style="display: inline">
              <div style="float: left">
                <% if current_user.voted_up_on?(comment) %>
                  <%= link_to '👍',comment_like_path(comment), method: :put, class:"icon-on" %>
                <% else %>
                  <%= link_to '👍',comment_like_path(comment), method: :put, class:"icon" %>
                <% end %>



                <% if current_user.voted_down_on?(comment) %>
                  <%= link_to '👎',comment_dislike_path(comment), method: :put, class:"icon-on" %>
                <% else %>
                  <%= link_to '👎',comment_dislike_path(comment), method: :put, class:"icon" %>
                <% end%>
              </div>

              <div style="float: right">
                <% if current_user.id == comment.user_id || current_user.try(:admin?) %>
                  <%= link_to '✎', comment_edit_path(comment), class:"icon" %>
                  <%= link_to '🗑️', comment_delete_path(comment),
                              :onclick => "return confirm('Are you sure you want to delete this comment?')", class:"icon" %>
                <% end %>
              </div>
            </div>
            <br>
            <br>
          <%   end %>
        </div>
      <% end %>
    <div class="container-text container-post"><%= will_paginate @comments , :class=>"centred flickr_pagination"%></div>
    <% else %>
      <div class="container-text div-padding">No comments written so far for this topic.</div>
    <% end %>
  <% if user_signed_in? %>
    <div class="container-title-new">
      <%= form_tag(comment_new_topic_path, method: :post) do %>
        <h4>Write a Comment</h4>
        <div class="centred">
          <%= text_area_tag 'body',nil,class: "comment-form",cols: 116, rows: 4 %>
          <br>
        <strong><%= submit_tag "Post", class:"big-button link"%></strong></div></div>
      <% end %>
  <% end %>
  </div>
<br>