config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :sign_out_via => [ :get, :delete ]
  resources :authors
  resources :books

  get 'conversations', to: 'conversations#index', as: 'conversations'
  get 'conversation/get_chat/:conversation_id', to: 'messages#get_conversation', as: 'get_conversation'
  get 'conversations/new/:sender_id/:receiver_id', to: 'conversations#create', as: 'create_conversation'
  post 'conversations/new/:sender_id/:receiver_id', to: 'conversations#create', as: 'new_conversation'
  get 'conversation/conv=:conversation_id', to: 'messages#index', as: 'conversation_messages'
  post 'conversation/new/:conversation_id', to: 'messages#create', as: 'conversation_messages_create'
  get 'users/index', to: 'users#index', as: 'user_index'
  get 'users/profile/:id/', to: 'users#profile', as: 'user_profile'
  get 'users/profile/:id/reviews/', to: 'users#reviews', as: 'user_reviews'
  get 'users/profile/:id/friends/', to: 'users#friends', as: 'user_friends'
  get 'user/profile/:id/forum', to: 'users#forum', as: 'user_forum'
  get 'user/profile/:id/recommandations', to: 'users#recommandations', as: 'user_recs'
  post 'user/profile/:id/comments/new', to:'comments#comment_new_user', as: 'comment_new_user'
  get 'users/profile/:id/list', to:'users#list', as: 'list'
  get 'users/profile/edit_list/:id_user_book/', to: 'users#details', as: 'list_book_details'
  patch 'users/profile/edit_list/:id_user_book/', to:'users#update_list', as: 'book_update_list_adv'
  get 'users/profile/edit_list/:id_user_book/remove', to:'users#remove_list', as: 'remove_list'
  post 'books/user_list/:id/', to:'books#add_to_list', as: 'book_add_list'
  patch 'books/user_list/:id/', to:'books#update_list', as: 'book_update_list'
  post 'book/:id/comments/new', to:'comments#comment_new_book', as: 'comment_new_book'
  get 'author/delete/:id', to: 'authors#destroy', as: 'author_delete'
  post 'author/:id/comments/new', to:'comments#comment_new_author', as: 'comment_new_author'
  get 'search_results', to: 'search#search', as: 'search'
  get 'myreviews/new/:book_id', to: 'reviews#new', as: 'review_new'
  post 'myreviews/new/:book_id/create', to: 'reviews#create', as: 'review_create'
  get 'myreviews/:review_id/edit', to: 'reviews#edit', as: 'review_edit'
  patch 'myreviews/:review_id/edit', to: 'reviews#update', as: 'review_update'
  get 'myreviews/:review_id/delete', to: 'reviews#destroy', as: 'review_delete'
  get 'myreviews/:review_id/like', to: 'reviews#like', as: 'review_like'
  get 'myreviews/:review_id/dislike', to: 'reviews#dislike', as: 'review_dislike'
  get 'books/reviews/:id', to: 'books#reviews', as: 'book_reviews'
  get 'books/editions/:id', to: 'books#editions', as: 'book_editions'
  get 'books/recommandations/:id', to: 'books#recommandations', as: 'book_recommandations'
  get 'books/stats/:id', to: 'books#stats', as: 'book_stats'
  delete 'books/delete/:id', to: 'books#destroy', as: 'book_delete'
  get 'books/delete/:id' => 'books#destroy'
  get 'book/:book_id/editions/new/', to: 'editions#new', as: 'edition_new'
  post 'book/:book_id/editions/new/create', to: 'editions#create', as: 'edition_create'
  get 'editions/:edition_id/delete', to: 'editions#destroy', as: 'edition_delete'
  get 'editions/:edition_id/edit', to: 'editions#edit', as: 'edition_edit'
  patch 'editions/:edition_id/edit', to: 'editions#update', as: 'edition_update'
  get 'comment/:comment_id/edit', to:'comments#edit', as: 'comment_edit'
  patch 'comment/:comment_id/edit', to:'comments#comment_update', as: 'comment_update'
  get 'comment/:comment_id/delete', to: 'comments#comment_delete', as: 'comment_delete'
  get 'comment/:comment_id/like', to: 'comments#like', as: 'comment_like'
  get 'comment/:comment_id/dislike', to: 'comments#dislike', as: 'comment_dislike'
  get 'add_friend/:id', to: 'users#add_friend', as: 'add_friend'
  get 'remove_friend/:id', to: 'users#remove_friend', as: 'remove_friend'
  get 'friend_requests', to: 'users#requests', as: 'friend_requests'
  get 'accept_request/:id', to: "users#accept_request", as: 'accept_request'
  get 'decline_request/:id', to: "users#decline_request", as: 'decline_request'
  get 'cancel_request/:id', to: 'users#cancel_request', as: 'cancel_request'
  get 'home', to: 'users#home', as: 'home'
  get 'recommandation/new/:book_id', to: 'recommandations#new', as: 'rec_new'
  post 'recommandation/create/:book_id', to: 'recommandations#create', as: 'rec_create'
  get 'recommandation/:id/destroy', to: 'recommandations#destroy', as: 'rec_destroy'
  get 'forum', to: 'category#forum', as: 'forum'
  get 'forum/:category_id', to: 'category#show', as: 'category'
  get 'forum/topic/:topic_id', to: 'topics#show', as: 'topic'
  post 'forum/topic/:topic_id', to:'comments#comment_new_topic', as: 'comment_new_topic'
  get 'forum/topic/:topic_id/like', to: 'topics#like', as: 'topic_like'
  get 'forum/topic/:topic_id/dislike', to: 'topics#dislike', as: 'topic_dislike'
  get 'forum/new/:category_id/topic/', to: 'topics#new', as: 'topic_new'
  post 'forum/new/:category_id/topic/', to: 'topics#create', as: 'topic_create'
  get 'forum/topic/:topic_id/edit', to: 'topics#edit', as: 'topic_edit'
  patch 'forum/topic/:topic_id/edit', to: 'topics#update', as: 'topic_update'
  get 'forum/topic/:topic_id/delete', to: 'topics#destroy', as: 'topic_delete'



  authenticated :user do
    root 'users#home', as: :authenticated_root
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end


  get "*path" => redirect("/"), alert: "This page does not exist"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  validates :lastName, presence: true
  has_many :books_to_authors, dependent: :destroy
  has_many :books, through: :books_to_authors
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>",mini: "30x30>" }, default_url: "/images/:style/No_Image_Available.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  has_many :comments, as: :commentable, dependent: :destroy
  include PublicActivity::Common

  GENDER_TYPES = ["Unspecified","Male", "Female"]


  def country_name
    country = self.country
    ISO3166::Country[country]
  end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :is_admin, only: [:new,:create,:edit,:update,:destroy]
  before_action :author_exist, only: [:edit,:update,:destroy,:show]
  def index
    @authors = Author.paginate(:page => params[:page], :per_page => 2).all
  end

  def show
    @author = Author.find(params[:id])
    @books = Book.joins(:books_to_authors).where(books_to_authors: {author_id: @author.id}).order('Title ASC')
    @comments = @author.comments
    if params[:sort]=="like"
      @comments = @comments.sort { |p1, p2| p2.get_likes.size <=> p1.get_likes.size}
    elsif params[:sort]=="dislike"
      @comments = @comments.sort { |p2, p1| p1.get_dislikes.size <=> p2.get_dislikes.size }
    elsif params[:sort]=="new"
      @comments = @comments.sort { |p1, p2| p2.created_at <=> p1.created_at}
    elsif params[:sort]=="old"
      @comments = @comments
    else
      @comments = @comments.sort { |p1, p2| p2.get_likes.size-p2.get_dislikes.size <=> p1.get_likes.size-p1.get_dislikes.size }
    end
    @comments = @comments.paginate(page: params[:page], per_page: 2)
    if params[:sort_b]=='title'
      @books = @books.sort { |p1, p2| p1.title.upcase <=> p2.title.upcase}
    elsif params[:sort_b]=='title_inv'
      @books = @books.sort { |p1, p2| p2.title.upcase <=> p1.title.upcase}
    elsif params[:sort_b]=='published_inv'
      @books = @books.reject(&:published) + @books.select(&:published).sort_by(&:published)
    elsif params[:sort_b]=='published'
      @books = @books.select(&:published).sort_by {|x| Date.today - x.published} + @books.reject(&:published)
    elsif params[:sort_b]=='score_inv'
      @books = @books.sort{ |p1,p2| Book.score(p1.id) <=> Book.score(p2.id) }
    elsif params[:sort_b]=='score'
      @books = @books.sort{ |p1,p2| Book.score(p2.id) <=> Book.score(p1.id) }
    elsif params[:sort_b] == 'popularity'
      @books = @books.sort{ |p1,p2| UsersToBook.joins(:book).where(book_id: p2.id).count <=> UsersToBook.joins(:book).where(book_id: p1.id).count}
    elsif params[:sort_b] == 'popularity_inv'
      @books = @books.sort{ |p1,p2| UsersToBook.joins(:book).where(book_id: p1.id).count <=> UsersToBook.joins(:book).where(book_id: p2.id).count}
    end
  end

  def edit
    @author = Author.find(params[:id])
  end


  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)

    if @author.save
      redirect_to @author, :notice => "New author added."
    else
      render 'new'
    end
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to @author, :notice => "The author has been updated."
    else
      render 'edit'
    end
  end


  def destroy
    @author = Author.find(params[:id])
    @author.destroy
    redirect_to authors_path, :notice => "The author has been deleted."
    end

  def is_admin
    if !current_user.try(:admin?)
      redirect_to root_path, :alert => "You don't have the rights to acces this page."
    end
  end

  def author_exist
    if not Author.exists?(params[:id])
    then redirect_to root_path, alert: 'The author does not exist.'
    end
  end

  private
  def author_params
    params.require(:author).permit(:lastName,:firstName, :bios,:death,:birth,:avatar,:gender,:country)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with model: @author, local: true do |form| %>

  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@author.errors.count, "error") %> prohibited
        this author from being saved:
      </h2>
      <ul>
        <% @author.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class= "row">
    <%= form.label "First Name", class: "label-form col-25 "  %>
    <%= form.text_field :firstName, class: "input-form col-75" %>
  </div>

  <div class= "row">
    <%= form.label "Last Name *", class: "label-form col-25 "  %>
    <%= form.text_field :lastName, class: "input-form col-75" %>
  </div>

  <div class= "row">
    <%= form.label :gender, class: "label-form col-25 " %>
    <%= form.select :gender,  User::GENDER_TYPES, {}, { :class => 'input-form select-form col-75' } %>
  </div>

  <div class= "row">
    <%= form.label :country, class: "label-form col-25 " %>
    <%= country_select("author", "country", {}, { :class => 'input-form select-form col-75' }) %>
  </div>

  <div class= "row">
    <%= form.label :bios, class: "label-form col-25 "  %>
    <%= form.text_area :bios, class: "input-form col-75" %>
  </div>

  <div class= "row">
    <%= form.label "Birth Date", class: "label-form col-25 "  %>
    <%= form.date_field :birth, as: :date, value: form.object.try(:strftime,"%m/%d/%Y"), class: "input-form col-75"%>
  </div>

  <div class= "row">
    <%= form.label "Death Date", class: "label-form col-25 "  %>
    <%= form.date_field :death, class: "input-form col-75" %>
  </div>

  <div class="row">
    <%= form.label :avatar, class: "label-form col-25 "  %>
    <%= form.file_field :avatar, { :class => 'search-button col-75' } %>
  </div>

  <div class= "row">
    <em class="label-form col-35">The fields marked with '*' are required.</em>
  </div>

  <%= form.submit class: 'big-button link' %>
<% end %>

app/views/authors/edit.html.erb
<div class="container-form">
<h1>Edit author</h1>
<%= render 'form' %>
</div>

app/views/authors/index.html.erb
<div class="container-text">
  <div class="container-title"><h1>
  All authors
  </h1></div>
  <table style="width:100%">
    <tr>
      <th>Image</th>
      <th><% if params[:sort]!='fname' %>
          <%= link_to 'First Name ▼',search_path(:search=>params[:search],:search_for=>'Authors',:sort=>'fname'),class: "link"%>
        <%else%>  <%= link_to 'First Name ▲',search_path(:search=>params[:search],:search_for=>'Authors',:sort=>'fname_inv'),class: "link"%>
        <% end %></th>
      <th><% if params[:sort]!='lname' %>
          <%= link_to 'Last Name ▼',search_path(:search=>params[:search],:search_for=>'Authors',:sort=>'lname'),class: "link"%>
        <%else%>  <%= link_to 'Last Name ▲',search_path(:search=>params[:search],:search_for=>'Authors',:sort=>'lname_inv'),class: "link"%>
        <% end %></th>
      <th>Bios</th>
      <th><% if params[:sort]!='birth' %>
          <%= link_to 'Birth Date ▼',search_path(:search=>params[:search],:search_for=>'Authors',:sort=>'birth'),class: "link"%>
        <%else%>  <%= link_to 'Birth Date ▲',search_path(:search=>params[:search],:search_for=>'Authors',:sort=>'birth_inv'),class: "link"%>
        <% end %></th>
      <th>Comments</th>
    </tr>
<% @authors.each do |author| %>
    <tr> <td><% if author.avatar.exists? %>
        <%= image_tag author.avatar.url(:thumb) %>
      <%else%> <%= image_tag('No_Image_Available.png', size: "100x100",alt: 'no_image') %>
      <% end %></td>
      <td><%= link_to author.firstName, author_path(author) %></td>
      <td><%= link_to author.lastName, author_path(author) %></td>
      <td><%= truncate(author.bios, :length => 80) %>
        <% if author.bios.length > 80 %>
          <%=link_to 'Read more', author_path(author) %>
        <% end %></td>
      <td><% if author.birth %>
          <%= author.birth %>
        <% else %>
          ?
        <% end %></td>

      <td><%= author.comments.count%></td>
    </tr>
  <% end %>
  </table><%= will_paginate @authors , :class=>"centred flickr_pagination"%></div>

app/views/authors/new.html.erb
<div class="container-form"><h1>New Author</h1>
  <%= render 'form' %></div>

app/views/authors/show.html.erb
<div class="div-container">
  <div id="container-book">
    <div class="centred">
      <div class="container-title">
  <h3>
    <% if @author.firstName%>
  <%= @author.firstName + " " + @author.lastName %>
      <% else %>
    <%= @author.lastName %>
      <% end %>
  </h3>
<% if current_user.try(:admin?) %>
<%= link_to '✎', edit_author_path(@author.id), class: "icon-link" %>
<%= link_to '🗑', author_delete_path(@author.id),
            method: :delete,
            :onclick=> "return confirm('Are you sure you want to delete this author from the database?')", class: "icon-link" %>
  <% end %></div>
      <div class="div-padding">
  <% if @author.avatar.exists? %>
    <%= image_tag @author.avatar.url(:medium) %>
      <%else%> <%= image_tag('No_Image_Available.png', size: "300x300",alt: 'no_image') %>
        <% end %></div></div>
    <div class="div-padding">
 <strong> Born:</strong> <% if (@author.birth) %>
  <%= @author.birth%>
    <% else %>
    Unknown
    <% end %>
  <br>
  <% if (@author.death) %>
 <strong> Died: </strong><%= @author.death%>
    <%end%>
  <br>
  <strong>Short Bios:</strong>
  <% if (@author.bios!=""&&@author.bios)%>
  <%= @author.bios %>
    <% else %>
  Unknown
    <% end %>
    <br>
    <strong>Gender:</strong> <% if @author.gender %>
      <%= @author.gender %>
    <% else %>
      Unspecified
    <% end %>
    <br>
    <strong>Lives in:</strong> <% if @author.country!='f' %>
      <%= @author.country_name %>
    <% else %>
      Unspecified
    <% end %>
  </div>
  </div>
<div class="container-reviews container-text">
  <div class="container-title div-padding">
    <h3><% if @author.firstName%>
        <%= @author.firstName + " " + @author.lastName %>
      <% else %>
        <%= @author.lastName%>
      <%end%>'s books</h3></div>
      <% if @books.count > 0 %>
    <table width="100%">
      <tr>
        <th>Image</th>
        <th><% if params[:sort_b]!='title' %>
            <%= link_to 'Title ▼',author_path(:id=>params[:id],:sort_b=>'title'),class: "link"%>
          <%else%>  <%= link_to 'Title ▲',author_path(:id=>params[:id],:sort_b=>'title_inv'),class: "link"%>
          <% end %></th>
        <th>Description</th>
        <th><% if params[:sort_b]!='published' %>
            <%= link_to 'Published ▼',author_path(:id=>params[:id],:sort_b=>'published'),class: "link"%>
          <%else%>  <%= link_to 'Published ▲',author_path(:id=>params[:id],:sort_b=>'published_inv'),class: "link"%>
          <% end %></th>
        <th><% if params[:sort_b]!='score' %>
            <%= link_to 'Score ▼',author_path(:id=>params[:id],:sort_b=>'score'),class: "link"%>
          <%else%>  <%= link_to 'Score ▲',author_path(:id=>params[:id],:sort_b=>'score_inv'),class: "link"%>
          <% end %></th>
        <th><% if params[:sort_b]!='popularity' %>
            <%= link_to 'Members ▼',author_path(:id=>params[:id],:sort_b=>'popularity'),class: "link"%>
          <%else%>  <%= link_to 'Members ▲',author_path(:id=>params[:id],:sort_b=>'popularity_inv'),class: "link"%>
          <% end %></th>
        <th>Reviews</th>
        <th>Comments</th>
      </tr>
      <% @books.each do |book| %>
        <tr>  <td>
      <% if book.avatar.exists? %>
        <%= image_tag book.avatar.url(:thumb) %>
      <%else%> <%= image_tag('No_Image_Available.png', size: "100x100",alt: 'no_image') %>
      <% end %></td>
        <td><%= link_to book.title, book_path(book) %></td>
        <td><%= truncate(book.description, :length => 60) %>
          <% if book.description.length > 60 %>
            <%=link_to 'Read more', book_path(book) %></td>
          <% end %>
          <td> <% if book.published %>
              <%= book.published %>
            <% else %>
              ?
            <% end %>
          </td>
          <td><% @avg_rat = Book.score(book.id)%>
            <%= (@avg_rat).round(2) %></td>
          <td><%= UsersToBook.joins(:book).where(book_id: book.id).count %></td>
          <td><%= Review.joins(:book).where(book_id: book.id).count %></td>
          <td><%= book.comments.count %></td>
          </tr>
        <%end%>
    </table>
        <% else %>
      No books found.
        <% end %>
    </div>
</div>
  <div class="container-reviews">
    <br>
    <div class="container-title-new">
      <h4 class="same-row-title">Comments</h4>

      <label class="dropdown" style="float: right; padding-top: 5px;"><div class="dropbtn link">Sort comments ▼</div> <div class="dropdown-content">
          <%= link_to "Best", author_path(@author) %>
          <%= link_to "Most Likes", author_path(@author, :sort => "like") %>
          <%= link_to "Most Disikes", author_path(@author, :sort => "dislike") %>
          <%= link_to "Oldest", author_path(@author, :sort => "old") %>
          <%= link_to "Newest", author_path(@author, :sort => "new") %>
        </div>
      </label>
    </div>

    <% if @comments.count > 0 %>
      <% @comments.each do |comment| %>
        <div class="container-text div-padding">
          <% if User.find(comment.user_id).avatar.exists? %>
            <%= image_tag User.find(comment.user_id).avatar.url(:mini) %>
          <% else %> <%= image_tag('No_Image_Available.png', size: "30x30", alt: 'no_image') %>
          <% end %>
          <%= link_to comment.user.username, user_profile_path(comment.user.username) %>
          <%= simple_format comment.body %>
          <br>
          <em>Posted at <%= comment.created_at %></em>
          <br>
          <%= comment.get_upvotes.size.to_s + " out of " + (comment.get_downvotes.size + comment.get_upvotes.size).to_s + " users found this comment helpful. " %>

          <br>
          <% if user_signed_in? %>

            <div style="display: inline">
              <div style="float: left">
                <% if current_user.voted_up_on?(comment) %>
                  <%= link_to '👍',comment_like_path(comment), method: :put, class:"icon-on" %>
                <% else %>
                  <%= link_to '👍',comment_like_path(comment), method: :put, class:"icon" %>
                <% end %>



                <% if current_user.voted_down_on?(comment) %>
                  <%= link_to '👎',comment_dislike_path(comment), method: :put, class:"icon-on" %>
                <% else %>
                  <%= link_to '👎',comment_dislike_path(comment), method: :put, class:"icon" %>
                <% end%>
              </div>

              <div style="float: right">
                <% if current_user.id == comment.user_id || current_user.try(:admin?) %>
                  <%= link_to '✎', comment_edit_path(comment), class:"icon" %>
                  <%= link_to '🗑️', comment_delete_path(comment),
                              :onclick => "return confirm('Are you sure you want to delete this comment?')", class:"icon" %>
                <% end %>
              </div>
            </div>
          <%   end %>
          <br>
          <br>
        </div>
      <% end %>
      <div class="container-text"><%= will_paginate @comments , :class=>"centred flickr_pagination"%></div>
    <% else %>
      <div class="container-text">No comments written so far for this book.</div>
    <% end %>
    <% if user_signed_in? %>
      <div class="container-title-new ">
        <%= form_tag(comment_new_author_path, method: :post) do %>
          <h4>Write a Comment</h4>
          <div class="centred">
            <%= text_area_tag 'body',nil,class: "comment-form",cols: 112, rows: 4 %>
            <br>
            <strong><%= submit_tag "Post", class: "big-button link"%></strong></div></div>
        <% end %>
    <% end %>
  </div>
</div>
<br>