config/routes.rb
Rails.application.routes.draw do


  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, :sign_out_via => [ :get, :delete ]
  resources :authors
  resources :books

  get 'conversations', to: 'conversations#index', as: 'conversations'
  get 'conversation/get_chat/:conversation_id', to: 'messages#get_conversation', as: 'get_conversation'
  get 'conversations/new/:sender_id/:receiver_id', to: 'conversations#create', as: 'create_conversation'
  post 'conversations/new/:sender_id/:receiver_id', to: 'conversations#create', as: 'new_conversation'
  get 'conversation/conv=:conversation_id', to: 'messages#index', as: 'conversation_messages'
  post 'conversation/new/:conversation_id', to: 'messages#create', as: 'conversation_messages_create'
  get 'users/index', to: 'users#index', as: 'user_index'
  get 'users/profile/:id/', to: 'users#profile', as: 'user_profile'
  get 'users/profile/:id/reviews/', to: 'users#reviews', as: 'user_reviews'
  get 'users/profile/:id/friends/', to: 'users#friends', as: 'user_friends'
  get 'user/profile/:id/forum', to: 'users#forum', as: 'user_forum'
  get 'user/profile/:id/recommandations', to: 'users#recommandations', as: 'user_recs'
  post 'user/profile/:id/comments/new', to:'comments#comment_new_user', as: 'comment_new_user'
  get 'users/profile/:id/list', to:'users#list', as: 'list'
  get 'users/profile/edit_list/:id_user_book/', to: 'users#details', as: 'list_book_details'
  patch 'users/profile/edit_list/:id_user_book/', to:'users#update_list', as: 'book_update_list_adv'
  get 'users/profile/edit_list/:id_user_book/remove', to:'users#remove_list', as: 'remove_list'
  post 'books/user_list/:id/', to:'books#add_to_list', as: 'book_add_list'
  patch 'books/user_list/:id/', to:'books#update_list', as: 'book_update_list'
  post 'book/:id/comments/new', to:'comments#comment_new_book', as: 'comment_new_book'
  get 'author/delete/:id', to: 'authors#destroy', as: 'author_delete'
  post 'author/:id/comments/new', to:'comments#comment_new_author', as: 'comment_new_author'
  get 'search_results', to: 'search#search', as: 'search'
  get 'myreviews/new/:book_id', to: 'reviews#new', as: 'review_new'
  post 'myreviews/new/:book_id/create', to: 'reviews#create', as: 'review_create'
  get 'myreviews/:review_id/edit', to: 'reviews#edit', as: 'review_edit'
  patch 'myreviews/:review_id/edit', to: 'reviews#update', as: 'review_update'
  get 'myreviews/:review_id/delete', to: 'reviews#destroy', as: 'review_delete'
  get 'myreviews/:review_id/like', to: 'reviews#like', as: 'review_like'
  get 'myreviews/:review_id/dislike', to: 'reviews#dislike', as: 'review_dislike'
  get 'books/reviews/:id', to: 'books#reviews', as: 'book_reviews'
  get 'books/editions/:id', to: 'books#editions', as: 'book_editions'
  get 'books/recommandations/:id', to: 'books#recommandations', as: 'book_recommandations'
  get 'books/stats/:id', to: 'books#stats', as: 'book_stats'
  delete 'books/delete/:id', to: 'books#destroy', as: 'book_delete'
  get 'books/delete/:id' => 'books#destroy'
  get 'book/:book_id/editions/new/', to: 'editions#new', as: 'edition_new'
  post 'book/:book_id/editions/new/create', to: 'editions#create', as: 'edition_create'
  get 'editions/:edition_id/delete', to: 'editions#destroy', as: 'edition_delete'
  get 'editions/:edition_id/edit', to: 'editions#edit', as: 'edition_edit'
  patch 'editions/:edition_id/edit', to: 'editions#update', as: 'edition_update'
  get 'comment/:comment_id/edit', to:'comments#edit', as: 'comment_edit'
  patch 'comment/:comment_id/edit', to:'comments#comment_update', as: 'comment_update'
  get 'comment/:comment_id/delete', to: 'comments#comment_delete', as: 'comment_delete'
  get 'comment/:comment_id/like', to: 'comments#like', as: 'comment_like'
  get 'comment/:comment_id/dislike', to: 'comments#dislike', as: 'comment_dislike'
  get 'add_friend/:id', to: 'users#add_friend', as: 'add_friend'
  get 'remove_friend/:id', to: 'users#remove_friend', as: 'remove_friend'
  get 'friend_requests', to: 'users#requests', as: 'friend_requests'
  get 'accept_request/:id', to: "users#accept_request", as: 'accept_request'
  get 'decline_request/:id', to: "users#decline_request", as: 'decline_request'
  get 'cancel_request/:id', to: 'users#cancel_request', as: 'cancel_request'
  get 'home', to: 'users#home', as: 'home'
  get 'recommandation/new/:book_id', to: 'recommandations#new', as: 'rec_new'
  post 'recommandation/create/:book_id', to: 'recommandations#create', as: 'rec_create'
  get 'recommandation/:id/destroy', to: 'recommandations#destroy', as: 'rec_destroy'
  get 'forum', to: 'category#forum', as: 'forum'
  get 'forum/:category_id', to: 'category#show', as: 'category'
  get 'forum/topic/:topic_id', to: 'topics#show', as: 'topic'
  post 'forum/topic/:topic_id', to:'comments#comment_new_topic', as: 'comment_new_topic'
  get 'forum/topic/:topic_id/like', to: 'topics#like', as: 'topic_like'
  get 'forum/topic/:topic_id/dislike', to: 'topics#dislike', as: 'topic_dislike'
  get 'forum/new/:category_id/topic/', to: 'topics#new', as: 'topic_new'
  post 'forum/new/:category_id/topic/', to: 'topics#create', as: 'topic_create'
  get 'forum/topic/:topic_id/edit', to: 'topics#edit', as: 'topic_edit'
  patch 'forum/topic/:topic_id/edit', to: 'topics#update', as: 'topic_update'
  get 'forum/topic/:topic_id/delete', to: 'topics#destroy', as: 'topic_delete'



  authenticated :user do
    root 'users#home', as: :authenticated_root
  end

  devise_scope :user do
    root to: "devise/sessions#new"
  end


  get "*path" => redirect("/"), alert: "This page does not exist"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :lastseenable
  validates_presence_of :username
  validates_uniqueness_of :username
  has_many :users_to_books, dependent: :destroy
  has_many :books, through: :users_to_books
  has_many :reviews, dependent: :destroy
  has_many :recommandations, dependent: :destroy
  has_many :topics, dependent: :destroy
  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>",friend: "80x80", mini: "30x30>"}, default_url: "/images/:style/No_Image_Available.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  acts_as_voter
  has_many :comments, as: :commentable, dependent: :destroy
  has_friendship
  validates_length_of :username, :maximum => 20
  include PublicActivity::Common


  def self.find_by_uid!(uid)

    if User.exists?(:username => uid)
      User.find_by(:username => uid)
    else
      User.find(uid)
    end

  end

  GENDER_TYPES = ["Unspecified","Male", "Female"]


  def country_name
    country = self.country
    ISO3166::Country[country]
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/concerns/users_helper.rb
module Concerns::UsersHelper
end

app/helpers/users/search_helper.rb
module Users::SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_userinfo.html.erb
  <div id="container-book">
    <div class="centred">
      <div class="container-title"><h1><%= @user.username %>'s profile</h1>
        <% if user_signed_in? %>
          <% if current_user != @user %>
            <% if current_user.friends_with?(@user) %>
              <%= link_to "Remove Friend", remove_friend_path(@user), class: "link" %>
            <% elsif current_user.pending_friends.include?(@user) %>
              <%= link_to "Cancel", cancel_request_path(@user), class: "link" %>
            <% else %>
              <%= link_to "Add Friend", add_friend_path(@user), class: "link" %>
            <% end %>
          | <%= link_to 'Start Conversation', create_conversation_path(sender_id: current_user.id, receiver_id: @user),target: :_blank, class: "link" %>
          <%end end%></div>
      <div class="div-padding">
        <% if @user.avatar.exists? %>
          <%= image_tag @user.avatar.url(:medium) %>
        <%else%> <%= link_to image_tag('No_Image_Available.png', size: "300x300",alt: 'no_image') %>
        <% end %></div></div>
    <div class="div-padding">
      <strong>Real Name:</strong> <% if @user.first_name || @user.last_name %>
        <%= @user.first_name + ' ' + @user.last_name %>
      <% else %>
        Unspecified
      <% end %>
      <br>
      <strong>Joined at:</strong> <%= @user.created_at.to_date.to_s %>
      <br>
      <strong>Birthday:</strong> <% if @user.birthday %>
        <%= @user.birthday %>
      <% else %>
        Unspecified
      <% end %>
      <br>
      <strong>Gender:</strong> <% if @user.gender %>
        <%= @user.gender %>
      <% else %>
        Unspecified
      <% end %>
      <br>
      <strong>Lives in:</strong> <% if @user.country!='f' %>
        <%= @user.country_name %>
      <% else %>
        Unspecified
      <% end %>
      <br>
      <strong>Profile Description: </strong> <% if @user.short_description %>
        <%= simple_format @user.short_description %>
      <% else %>
        Unspecified
      <% end %>
      <h4>Friends</h4>
      <div class="out">
        <% if @user.friends.count > 0 %>
     <% @user.friends.sample(3).each do |friend| %>
      <figure class="fig-pic">
        <% if friend.avatar.exists? %>
          <%= image_tag friend.avatar.url(:friend) %>
        <%else%> <%= image_tag('No_Image_Available.png', size: "80x80",alt: 'no_image') %>
        <% end %>
        <figcaption class="centred" style="font-size: 12px">
        <%= link_to friend.username, user_profile_path(friend.username) %>
        </figcaption>
      </figure>
        <% end %>
          <% else %>
        This user doesn't have any friends.
          <% end %>
      </div>
      <% if @user.friends.count > 3 %>
        <%= link_to 'More friends...', user_friends_path %>
        <% end %>
    </div></div>

  <div class="container-book-description">
    <label class="container-title-new"><%= link_to 'Profile', user_profile_path, :class => "link" %></label>
    <label class="container-title-new"><%= link_to 'Book List', list_path, :class => "link" %></label>
    <label class="container-title-new"><%= link_to 'Reviews', user_reviews_path, :class => "link" %></label>
    <label class="container-title-new"><%= link_to 'Friends', user_friends_path, :class => "link" %></label>
    <label class="container-title-new"><%= link_to 'Recommendations', user_recs_path, :class => "link" %></label>
    <label class="container-title-new"><%= link_to 'Forum Activity', user_forum_path, :class => "link" %></label>
  </div>

app/views/users/details.erb
<% if user_signed_in? %>

    <div class="container-form">
      <h1>Edit your entry in the list for the book <%=link_to @book.title,book_path(@book) %>: </h1>
      <% if @book.avatar.exists? %>
        <%= image_tag @book.avatar.url(:medium) %>
      <%else%> <%= image_tag('No_Image_Available.png', size: "300x300",alt: 'no_image') %>
      <% end %>
        <%= form_for(@users_to_book, url: list_book_details_path(@users_to_book.id), html: {method: "patch"}) do |f| %>

        <div class="row"><%= f.label "Score", class: "label-form col-25 " %>
        <%= f.select 'rating', options_for_select( @ratings.map {|s| [if s.score!=nil
                                                                             s.score
                                                                           else '(Nothing)'
                                                                           end,s.id]}, @book_rating ),{}, class: "select-form col-75" %></div>

        <div class="row"><%= f.label "Your Status: ", class: "label-form col-25 " %>
        <%= f.select :shelf, options_for_select( @shelves.map {|s| [s.status,s.id]}, @book_shelf ), {}, class: "select-form col-75" %></div>

        <div class="row">
        <%= f.label "Started Reading on: ", class: "label-form col-25 " %>
        <%= f.date_field :start_reading, as: :date, value: try(:strftime,"%d/%m/%Y"), class: "input-form col-75"%>
        </div>
        <div class="row">
        <%= f.label "Finished Reading on: ", class: "label-form col-25 " %>
        <%= f.date_field :end_reading, as: :date, value: try(:strftime,"%d/%m/%Y"), class: "input-form col-75"%>
        </div>
        <div class="row">
        <%= f.label "Notes: ", class: "label-form col-25 " %>
        <%= f.text_area :notes, class: "input-form col-75" %>
        </div>
        <%= f.submit "Update", class: "big-button link" %>
        <br>
        <%= link_to 'Remove', remove_list_path(params[:id_user_book]), :onclick=> "return confirm('Are you sure you want to remove this book from your list?')", class: "link"%>
      <% end %>
    </div>
<%end%>

app/views/users/forum.html.erb
<div>
  <%= render 'userinfo' %>
  <div class="container-reviews">
    <div class="container-title-new">
      <h4>Forum activity</h4>
    </div>
    <% if @posts.count > 0 %>
      <% @posts.each do |activity| %>
        <% if activity.trackable %>
          <div class="container-text div-padding">
            <% if activity.key=="comment.commented_on_topic" %>
            <%= link_to activity.owner.username %> replied on the topic
            <%=link_to activity.trackable.commentable.title, topic_path(activity.trackable.commentable.id) %>.
            <br>
            <%= simple_format activity.trackable.body %>
            <%elsif activity.key=="topic.topic" %>
              <%= link_to activity.owner.username %> created the topic  <%= link_to activity.trackable.title, user_profile_path(activity.trackable) %>
              in the category <%= link_to activity.trackable.category.name, category_path(activity.trackable.category) %>.
              <br>
              <%= simple_format activity.trackable.body %>
              <% end %>
            <br>
            <em>Added at <%= activity.created_at %></em>
            <br>
          </div>
        <% elsif activity.trackable_type=="Comment"
             Comment.delete_activities(activity.trackable_id)
           elsif activity.trackable_type=="Topic"
             Topic.delete_activities(activity.trackable_id)
           end %>
      <% end %>
      <div class="container-text"><%= will_paginate @posts , :class=>"centred flickr_pagination"%></div>
    <% else %>
      <div class="container-text"> No recommandations made by this user so far.</div>
    <% end %>
  </div>
</div>

app/views/users/profile.html.erb
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
<%= javascript_include_tag "application" %>

<div style="padding-left: 5px; padding-right: 5px; padding-bottom: 5px">
  <div class="div-container">
    <%= render 'userinfo' %>

  <div class="container-reviews container-text">
    <div class="container-title"><h4>Users Stats</h4></div>
    <div class="div-padding">
    <h4 class="centred">Number of books in every list</h4>
    <%= bar_chart @status%>
    <h4 class="centred">Number of books by rating</h4>
    <%= bar_chart @ratings%>
      <strong>Total List Entries:</strong> <%= @reading + @completed + @dropped + @p2r %>
      <br>
    <strong>Average list score:</strong>  <% if @avg_rat.nan? %>
      Nothing
    <% else %>
      <%= (@avg_rat).round(2) %>
    <% end %>
      <br>

      <strong>Reviews: </strong> <%= @reviews.count %>
      <br>
      <strong>Reviews Score: </strong> <%= @review_sum %>
      <br>
      <strong>Forum topics: </strong> <%= @topic_count %>
      <br>
      <strong>Comments: </strong> <%= @comments_count %>
      <br>
      <strong>Recommandations: </strong> <%= @recs_count %>
    <br>
    <br>
    </div>
  </div>

    <div class="container-reviews">
      <div class="container-title-new">
        <h4 class="same-row-title">Comments</h4>
        <label class="dropdown" class="dropdown" style="float: right; padding-top: 5px;"><div class="dropbtn link">Sort comments ▼</div> <div class="dropdown-content">
          <%= link_to "Best", user_profile_path(@user) %>
          <%= link_to "Most Likes", user_profile_path(@user, :sort => "like") %>
          <%= link_to "Most Disikes", user_profile_path(@user, :sort => "dislike") %>
          <%= link_to "Oldest", user_profile_path(@user, :sort => "old") %>
          <%= link_to "Newest", user_profile_path(@user, :sort => "new") %>
        </div>
        </label>
      </div>
      <% if @comments.count > 0 %>
        <% @comments.each do |comment| %>
        <div class="container-text div-padding">
            <% if User.find(comment.user_id).avatar.exists? %>
              <%= image_tag User.find(comment.user_id).avatar.url(:mini) %>
            <% else %> <%= image_tag('No_Image_Available.png', size: "30x30", alt: 'no_image') %>
            <% end %>
            <%= link_to comment.user.username, user_profile_path(comment.user.username) %>
            <%= simple_format comment.body %>
            <br>
            <em>Posted at <%= comment.created_at %></em>
            <br>
            <%= comment.get_upvotes.size.to_s + " out of " + (comment.get_downvotes.size + comment.get_upvotes.size).to_s + " users found this comment helpful. " %>

            <br>
            <% if user_signed_in? %>

              <div style="display: inline">
                <div style="float: left">
                  <% if current_user.voted_up_on?(comment) %>
                    <%= link_to '👍',comment_like_path(comment), method: :get, class:"icon-on" %>
                  <% else %>
                    <%= link_to '👍',comment_like_path(comment), method: :get, class:"icon" %>
                  <% end %>



                  <% if current_user.voted_down_on?(comment) %>
                    <%= link_to '👎',comment_dislike_path(comment), method: :get, class:"icon-on" %>
                  <% else %>
                    <%= link_to '👎',comment_dislike_path(comment), method: :get, class:"icon" %>
                  <% end%>
                </div>

                <div style="float: right">
                  <% if current_user.id == comment.user_id || current_user.try(:admin?) %>
                    <%= link_to '✎', comment_edit_path(comment), class:"icon" %>
                    <%= link_to '🗑️', comment_delete_path(comment),
                                :onclick => "return confirm('Are you sure you want to delete this comment?')", class:"icon" %>
                  <% end %>
                </div>
              </div>
              <br>
              <br>
            <%   end %>
        </div>
        <% end %>

        <%= will_paginate @comments , :class=>"centred flickr_pagination"%>
      <% else %>
        <div class="container-text div-padding"> No comments written so far for this book.</div>
      <% end %>
      <% if user_signed_in? %>
        <div class="container-title-new">
          <%= form_tag(comment_new_user_path, method: :post) do %>
            <h4>Write a Comment</h4>
            <div class="centred">
              <%= text_area_tag 'body',nil,class: "comment-form",cols: 110, rows: 4 %>
              <br>
            <strong><%= submit_tag "Post", class: "big-button link"%></strong></div></div>
          <% end %>
      <% end %>
    </div>
  </div>

</div>

app/views/users/requests.html.erb
<div class="container-form"><h1>Friend Requests</h1>
  <% if @requests.count > 0 %>
  <% @requests.each do |friend| %>
    <div class="row">
      <div class="left">
    <% if friend.avatar.exists? %>
      <%= image_tag friend.avatar.url(:thumb) %>
    <%else%> <%= image_tag('No_Image_Available.png', size: "100x100",alt: 'no_image') %>
      <% end %>
    <%= link_to friend.username, user_profile_path(friend.username), class: "link" %>
      </div>
      <div class="right-accept">
    <%= link_to "Accept", accept_request_path(friend.id), class: "big-button link" %>
      <%= link_to "Decline", decline_request_path(friend.id), class: "big-button link" %>
      </div>
    </div>
    <% end %>
    <% else %>
  No friend requests recieved so far.
  <% end %>
  </div>

app/views/users/reviews.html.erb
<div>
  <%= render 'userinfo' %>

<div class="container-reviews">
<div class="container-title-new">
  <h4 class="same-row-title">Reviews (<%= @reviews.count %>)</h4>
  <label class="dropdown" style="float: right; padding-top: 5px">
  <div class="dropbtn link" >Sort reviews ▼</div> <div class="dropdown-content">
  <%= link_to "Best", user_reviews_path(@user) %>
  <%= link_to "Most Likes", user_reviews_path(@user, :sort => "like") %>
  <%= link_to "Most Disikes", user_reviews_path(@user, :sort => "dislike") %>
  <%= link_to "Oldest", user_reviews_path(@user, :sort => "old") %>
  <%= link_to "Newest", user_reviews_path(@user, :sort => "new") %>
  </div>
  </label>
</div>
<% if @reviews.count > 0 %>
  <% @reviews.each do |review| %>
    <div class="container-text div-padding">
      <% if Book.find(review.book_id).avatar.exists? %>
        <%= image_tag Book.find(review.book_id).avatar.url(:thumb), :style=>"float: left" %>
      <% else %> <%= image_tag('No_Image_Available.png', size: "100x100", alt: 'no_image', style: "float: left" ) %>
      <% end %>
      <strong>Review for: </strong><%= link_to review.book.title, book_path(review.book_id) %>
      <br>
      <strong>Score:</strong>  <%= review.rating.score %>
      <br>
      <strong>Posted : </strong><%= review.created_at %>
      <br>
      <em><%= review.get_upvotes.size.to_s + " out of " + (review.get_downvotes.size + review.get_upvotes.size).to_s + " users found this review helpful. " %></em>

      <br>
      <br>
      <%= simple_format review.content %>
      <% if user_signed_in? %>

        <div style="display: inline">
          <div style="float: left">
            <% if current_user.voted_up_on?(review) %>
              <%= link_to '👍',review_like_path(review), method: :put, class:"icon-on" %>
            <% else %>
              <%= link_to '👍',review_like_path(review), method: :put, class:"icon" %>
            <% end %>



            <% if current_user.voted_down_on?(review) %>
              <%= link_to '👎',review_dislike_path(review), method: :put, class:"icon-on" %>
            <% else %>
              <%= link_to '👎',review_dislike_path(review), method: :put, class:"icon" %>
            <% end%>
          </div>

          <div style="float: right">
            <% if current_user.id == review.user_id || current_user.try(:admin?) %>
              <%= link_to '✎', review_edit_path(review), class:"icon" %>
              <%= link_to '🗑️', review_delete_path(review),
                          :onclick => "return confirm('Are you sure you want to delete this review?')", class:"icon" %>
            <% end %>
          </div>
        </div>
      <%   end %>
      <br>
      <br>
    </div>
  <% end %>
    <div class="container-text"><%= will_paginate @reviews , :class=>"centred flickr_pagination"%></div>
<% else %><div class="container-text">This user doesn't have any reviews.</div>
  <br>
<% end %>
</div>
</div>